export const CATEGORY_VALUE = "CATEGORY_VALUE";
export const TYPE_VALUE = "TYPE_VALUE"; 
export const QUESTION_VALUE = "QUESTION_VALUE";
export const QUESTION_INDEX = "QUESTION_INDEX";
export const SCORE_VALUE = "SCORE_VALUE";
export const ATTEMPT_VALUE = "ATTEMPT_VALUE";
export const CATEGORY = "CATEGORY";
export const SELECTED_VALUES = "SELECTED_VALUES";     